name: Renovate
on:
  workflow_dispatch: # allows manual one-off run

permissions:
  contents: write   # ðŸ‘ˆ allow pushing branches
  pull-requests: write   # ðŸ‘ˆ allow creating PRs
  
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: tschut/renovate-maven-wrapper-error
          LOG_LEVEL: debug
